language: python
services:
    - docker
before_install:
    - docker build . -f docker/Dockerfile -t igormcsouza/movie-review-plus:backend-test
script:
    - docker run igormcsouza/movie-review-plus:backend-test python -c "import classifier"